# Generated by Django 3.1.7 on 2021-05-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kcrops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kcrop_image', models.ImageField(upload_to='pics')),
                ('kcrop_name', models.CharField(max_length=50)),
                ('kcrop_description', models.TextField()),
                ('kcrop_url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='rcrops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcrop_image', models.ImageField(upload_to='pics')),
                ('rcrop_name', models.CharField(max_length=50)),
                ('rcrop_description', models.TextField()),
                ('rcrop_url', models.CharField(max_length=50)),
            ],
        ),
    ]
