# Generated by Django 3.1.7 on 2021-05-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cropmsp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msp_crop_title', models.CharField(max_length=50)),
                ('crop_curr_price', models.IntegerField()),
            ],
        ),
    ]
