# Generated by Django 3.1.7 on 2021-05-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropmsp',
            name='crop_curr_price',
        ),
        migrations.AddField(
            model_name='cropmsp',
            name='crop_price',
            field=models.IntegerField(default=0),
        ),
    ]
